services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      BASE_BACKEND_URL: ${VITE_BASE_BACKEND_URL}
      BASE_FRONTEND_URL: ${VITE_BASE_FRONTEND_URL}
