services:
  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
